# Docker Compose override for development
# This file extends docker-compose.yml with development-specific settings

version: '3.8'

services:
  # Development overrides for the application
  app:
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
      LOGGING_LEVEL_COM_ECOM_BACKEND: DEBUG
      APP_DEBUG: true
    volumes:
      # Mount source code for hot reload (if using dev tools)
      - ./src:/app/src:ro
      # Mount logs for easy access
      - ./logs:/app/logs
    ports:
      # Expose debug port for remote debugging
      - "5005:5005"
    command: >
      sh -c "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
             $$JAVA_OPTS
             -Djava.security.egd=file:/dev/./urandom
             -jar app.jar"

  # Development database with exposed data
  mysql:
    environment:
      # More verbose logging for development
      MYSQL_GENERAL_LOG: 1
      MYSQL_GENERAL_LOG_FILE: /var/log/mysql/general.log
    volumes:
      # Mount logs for debugging
      - ./logs/mysql:/var/log/mysql
    ports:
      # Expose MySQL port for external connections  
      - "3307:3306"

  # Development Elasticsearch with more verbose logging
  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "logger.level=DEBUG"

  # Add a database administration tool for development
  adminer:
    image: adminer:4.8.1
    container_name: ecommerce-adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - ecommerce-network

  # Elasticsearch Head plugin for development
  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    container_name: ecommerce-es-head
    ports:
      - "9100:9100"
    depends_on:
      - elasticsearch
    networks:
      - ecommerce-network
